// Mocks generated by Mockito 5.0.16 from annotations
// in mobile_endoendo/test/widget/dashboard_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mobile_endoendo/repositories/articles_repository.dart' as _i2;
import 'package:mobile_endoendo/repositories/data/article.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ArticlesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesRepository extends _i1.Mock
    implements _i2.ArticlesRepository {
  MockArticlesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Article>> getNews() =>
      (super.noSuchMethod(Invocation.method(#getNews, []),
              returnValue: Future<List<_i4.Article>>.value(<_i4.Article>[]))
          as _i3.Future<List<_i4.Article>>);

  @override
  // ignore: unnecessary_overrides
  String toString() => super.toString();
}
